
atmosphere-grid:
  bottom: 0.0
  top: atmospherefile
  number-of-layers: 100

planet:
  planet-mass: 6.39e26
  planet-radius: 3.3895e8
  surface-albedo: 0.2
  solar-zenith-angle: 60.0
  photon-scale-factor: 0.432
  hydrogen-escape: {type: diffusion limited}
  water: {fix-water-in-troposphere: false, gas-rainout: false, water-condensation: false}

particles:
- {name: H2Oaer, RH-condensation: 0.1}
    
boundary-conditions:
# Fixed surface pressures based on 6.3 bar total.
- name: H2O
  lower-boundary: {type: press, press: 1.0e6}
  upper-boundary: {type: veff, veff: 0.0}
- name: CO2
  lower-boundary: {type: press, press: 5985} # 95%
  upper-boundary: {type: veff, veff: 0.0}
- name: N2
  lower-boundary: {type: press, press: 302.4} # 4.8% (I lump Ar and N2 together)
  upper-boundary: {type: veff, veff: 0.0}

# Vdeps based on Zahnle et al. (2008)
- name: H2O2
  lower-boundary: {type: vdep, vdep: 0.02}
  upper-boundary: {type: veff, veff: 0.0}
- name: O3
  lower-boundary: {type: vdep, vdep: 0.02}
  upper-boundary: {type: veff, veff: 0.0}