atmosphere-grid:
  number-of-layers: 50
  
planet:
  planet-mass: 6.39e26
  planet-radius: 3.3895e8
  surface-albedo: 0.1
  number-of-zenith-angles: 4
  photon-scale-factor: 0.432

optical-properties:
  ir:
    k-method: RandomOverlapResortRebin
    opacities: {k-distributions: on, CIA: on, rayleigh: on, photolysis-xs: on,
    particle-xs: [{name: Dust, data: marsdust}]}
  solar:
    k-method: RandomOverlapResortRebin
    opacities: {k-distributions: on, CIA: on, rayleigh: on, photolysis-xs: on,
    particle-xs: [{name: Dust, data: marsdust}]}